"""owner in meet

Revision ID: 4486d1d24f83
Revises: aa93525403c6
Create Date: 2023-06-06 17:17:04.255595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4486d1d24f83'
down_revision = 'aa93525403c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meets', sa.Column('owner', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_meets_owner'), 'meets', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meets_owner'), table_name='meets')
    op.drop_column('meets', 'owner')
    # ### end Alembic commands ###
