"""positions

Revision ID: ac83fbdf9d8c
Revises: a4ca9a326162
Create Date: 2023-06-05 14:31:10.371637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac83fbdf9d8c'
down_revision = 'a4ca9a326162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('orientation', sa.String(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_client_id'), 'position', ['client_id'], unique=False)
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.create_index(op.f('ix_position_name'), 'position', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_name'), table_name='position')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_index(op.f('ix_position_client_id'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
